name: Compare files in PR and Main Branch
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  compare_files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Compare files
      run: |
        pr_files=$(git diff-tree --no-commit-id --name-only -r ${{ github.event.pull_request.head.sha }})
        main_files=$(git diff-tree --no-commit-id --name-only -r ${{ github.event.pull_request.base.sha }})
        echo "Pull Request Files: $pr_files"
        echo "Main Branch Files: $main_files"
        for line in $pr_files; do
          # Extract the unique number prefix from the file name
          prefix=$(echo $line | grep -o -E '^[vmu][0-9]+'|sed 's/[vmu]//')
          echo "Checking prefix: $prefix"
          if echo "$main_files" | grep -q "^[vmu]$prefix"; then
            echo "A file with prefix $prefix already exists in main branch. Blocking pull request from merging."
            exit 1
          fi
        done
  get_file_names:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get file names
      run: |
        cd file_pattern_test
        pr_files=$(find . -type f -not -path '*/\.*')
        echo "Pull Request Files: $pr_files"
        for file in $pr_files; do
          prefix=$(echo $file | grep -o -E '^[vmu][0-9]+'|sed 's/[vmu]//')
          echo "File name: $file, Prefix: $prefix"
        done
  
        





