name: Compare files in PR and Main Branch
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  compare_files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Compare files
      run: |
        pr_files=$(git log --pretty=format: --name-only --diff-filter=AMR --no-merges $GITHUB_SHA...$GITHUB_HEAD_SHA)
        distinct_pr_files=$(echo "$pr_files" | grep "file_pattern_test" | tr ' ' '\n' | sort -u)
        for file in ${distinct_pr_files}; do
          path=$(dirname $file)
          echo "Folder: $path"
          pr_prefix=$(basename "$file" | cut -d'_' -f1)
          pr_prefexes=$pr_prefix
          version=$(git show HEAD:$path)
          main_prefix=$(basename "$version" | cut -d'_' -f1)
            if [ "$pr_prefix" == "$main_prefix" ]; then
                echo "prefixes matched. Setting status check to failure"
                # Set the commit status to failure using the Github API
                curl -H "Authorization: ${{ secrets.GITHUB_TOKEN }}" -X PUT -d '{"state": "failure", "context": "required", "description": "The prefixes of the files in the PR match those in the main branch. Please update the prefix before merging."}' https://api.github.com/repos/${{ github.repository }}/statuses/${{github.event.pull_request.head.sha}}
                exit 1
            else
                echo "prefixes do not match. Setting status check to success"
                # Set the commit status to success using the Github API
                curl -H "Authorization: ${{ secrets.GITHUB_TOKEN }}" -X PUT -d '{"state": "success", "context": "required", "description": "The prefixes of the files in the PR do not match those in the main branch. You can merge."}' https://api.github.com/repos/${{ github.repository }}/statuses/${{github.event.pull_request.head.sha}}
                exit 0
            fi
        done
      
  
        





