name: Extract files from PR
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  extract_files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Extract files
      run: |
        git diff-tree --no-commit-id --name-only -r ${{ github.event.pull_request.head.sha }} > files.txt
        while read line; do
          mkdir -p $(dirname $line)
          mv $line extracted_files/$line
        done < files.txt
